import AppShell from '@/components/AppShell';
import { createServerSupabaseClient } from '@/lib/supabase/server';

export default async function AdminAttendancePage({searchParams}:{searchParams:Promise<{date?:string}>}){
 const params=await searchParams; const date=params.date||new Date().toISOString().slice(0,10); const supabase=await createServerSupabaseClient();
 const {data:{user}}=await supabase.auth.getUser(); const {data:p}=await supabase.from('profiles').select('role').eq('id',user?.id??'').single();
 if(!p||!['manager','admin'].includes(p.role)) return <AppShell><Denied/></AppShell>;
 const {data}=await supabase.from('attendance').select('*,profiles(full_name,email)').eq('attendance_date',date).order('check_in_at',{ascending:true});
 return <AppShell><div><p className="text-sm font-semibold text-indigo-600">Operations</p><h1 className="mt-1 text-3xl font-bold">Attendance records</h1><form className="surface mt-6 flex flex-col gap-3 rounded-2xl p-4 sm:flex-row sm:items-end"><label className="text-sm font-medium">Date<input name="date" type="date" defaultValue={date} className="mt-2 block rounded-xl border border-slate-200 bg-white px-3 py-2 text-sm"/></label><button className="rounded-xl bg-slate-950 px-4 py-2.5 text-sm font-semibold text-white">Filter</button></form><div className="surface mt-6 overflow-hidden rounded-2xl"><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="bg-slate-50 text-slate-500"><tr><th className="px-5 py-3">Instructor</th><th className="px-5 py-3">Date</th><th className="px-5 py-3">Check-in</th><th className="px-5 py-3">Status</th><th className="px-5 py-3">Selfie</th></tr></thead><tbody className="divide-y divide-slate-100">{(data??[]).map(a=><tr key={a.id}><td className="px-5 py-4"><div className="font-medium">{a.profiles?.full_name}</div><div className="text-xs text-slate-400">{a.profiles?.email}</div></td><td className="px-5 py-4">{a.attendance_date}</td><td className="px-5 py-4">{new Date(a.check_in_at).toLocaleTimeString('en-IN',{hour:'2-digit',minute:'2-digit'})}</td><td className="px-5 py-4">{a.status}</td><td className="px-5 py-4 text-xs text-slate-400">{a.selfie_path}</td></tr>)}{(!data||data.length===0)&&<tr><td colSpan={5} className="px-5 py-12 text-center text-slate-400">No records for this date.</td></tr>}</tbody></table></div></div></div></AppShell>;
}
function Denied(){return <div className="surface rounded-3xl p-10 text-center"><h1 className="text-2xl font-bold">Access denied</h1></div>}
