'use client';

import { useState } from 'react';
import { Download, FileText } from 'lucide-react';
import { jsPDF } from 'jspdf';
import AppShell from '@/components/AppShell';
import { createBrowserSupabaseClient } from '@/lib/supabase/client';

export default function ReportsPage(){
 const [from,setFrom]=useState(new Date().toISOString().slice(0,7)+'-01'); const [to,setTo]=useState(new Date().toISOString().slice(0,10)); const [busy,setBusy]=useState(false); const [error,setError]=useState('');
 async function generate(){
  setBusy(true);setError('');
  try { const supabase=createBrowserSupabaseClient(); const {data:{user}}=await supabase.auth.getUser(); if(!user)throw new Error('Session expired.'); const {data:me}=await supabase.from('profiles').select('role').eq('id',user.id).single(); if(!me||!['manager','admin'].includes(me.role))throw new Error('You do not have report access.'); const {data}=await supabase.from('attendance').select('attendance_date,check_in_at,status,profiles(full_name)').gte('attendance_date',from).lte('attendance_date',to).order('attendance_date',{ascending:true}); const doc=new jsPDF(); doc.setFontSize(18);doc.text('RANCHO LABS',14,18);doc.setFontSize(13);doc.text('INSTRUCTOR ATTENDANCE REPORT',14,27);doc.setFontSize(10);doc.text(`Report Period: ${from} to ${to}`,14,36);let y=48;doc.setFontSize(9);doc.text('Instructor',14,y);doc.text('Date',85,y);doc.text('Check-in',120,y);doc.text('Status',155,y);y+=7;(data??[]).forEach((r:any)=>{if(y>280){doc.addPage();y=18;} doc.text(String(r.profiles?.full_name??''),14,y);doc.text(String(r.attendance_date),85,y);doc.text(new Date(r.check_in_at).toLocaleTimeString('en-IN',{hour:'2-digit',minute:'2-digit'}),120,y);doc.text(String(r.status),155,y);y+=6;});doc.setFontSize(10);doc.text(`Total check-ins: ${(data??[]).length}`,14,290);doc.save(`rancho-labs-attendance-${from}-to-${to}.pdf`); } catch(e){setError(e instanceof Error?e.message:'Unable to generate report.');} finally{setBusy(false);} }
 return <AppShell><div className="mx-auto max-w-3xl"><p className="text-sm font-semibold text-indigo-600">Reporting</p><h1 className="mt-1 text-3xl font-bold">Attendance reports</h1><p className="mt-1 text-slate-500">Generate a clean PDF for a selected date range.</p><div className="surface mt-7 rounded-3xl p-7"><div className="flex items-center gap-3"><div className="rounded-xl bg-indigo-50 p-3 text-indigo-600"><FileText/></div><div><h2 className="font-semibold">PDF report</h2><p className="text-sm text-slate-500">Selfies are intentionally excluded from the standard report to keep files small.</p></div></div><div className="mt-6 grid gap-4 sm:grid-cols-2"><label className="text-sm font-medium">From<input type="date" value={from} onChange={e=>setFrom(e.target.value)} className="mt-2 block w-full rounded-xl border border-slate-200 px-3 py-2.5"/></label><label className="text-sm font-medium">To<input type="date" value={to} onChange={e=>setTo(e.target.value)} className="mt-2 block w-full rounded-xl border border-slate-200 px-3 py-2.5"/></label></div>{error&&<div className="mt-4 rounded-xl bg-red-50 px-3 py-3 text-sm text-red-700">{error}</div>}<button onClick={generate} disabled={busy} className="mt-6 inline-flex items-center gap-2 rounded-xl bg-slate-950 px-5 py-3 text-sm font-semibold text-white disabled:opacity-60"><Download className="h-4 w-4"/>{busy?'Generating…':'Generate PDF'}</button></div></div></AppShell>;
}
