'use client';

import { FormEvent, useState } from 'react';
import { Eye, EyeOff, LockKeyhole, Mail, ShieldCheck } from 'lucide-react';
import { createBrowserSupabaseClient } from '@/lib/supabase/client';

export default function LoginPage() {
  const supabase = createBrowserSupabaseClient();
  const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [show, setShow] = useState(false); const [busy, setBusy] = useState(false); const [error, setError] = useState('');
  async function submit(e: FormEvent) { e.preventDefault(); setBusy(true); setError(''); const { error } = await supabase.auth.signInWithPassword({ email, password }); if (error) { setError(error.message); setBusy(false); return; } window.location.href = '/dashboard'; }
  async function reset() { if (!email) { setError('Enter your email first.'); return; } const { error } = await supabase.auth.resetPasswordForEmail(email, { redirectTo: `${window.location.origin}/login` }); setError(error ? error.message : 'Password reset email sent.'); }
  return <main className="min-h-screen grid-pattern relative overflow-hidden flex items-center justify-center p-6"><div className="absolute -top-28 -left-20 h-80 w-80 rounded-full bg-indigo-400/20 blur-3xl"/><div className="absolute -bottom-32 -right-24 h-96 w-96 rounded-full bg-cyan-300/20 blur-3xl"/><section className="surface w-full max-w-md rounded-3xl p-8 relative"><div className="mb-8 flex items-center gap-3"><div className="h-12 w-12 rounded-2xl bg-gradient-to-br from-indigo-600 to-cyan-500 text-white flex items-center justify-center"><ShieldCheck/></div><div><p className="text-xs font-semibold uppercase tracking-[.2em] text-indigo-600">Rancho Labs</p><h1 className="text-xl font-bold">Instructor Attendance</h1></div></div><h2 className="text-2xl font-bold">Welcome back</h2><p className="mt-1 text-sm text-slate-500">Sign in to securely record your attendance.</p><form onSubmit={submit} className="mt-7 space-y-4"><label className="block text-sm font-medium">Email<div className="mt-2 relative"><Mail className="absolute left-3 top-3.5 h-4 w-4 text-slate-400"/><input required type="email" value={email} onChange={e=>setEmail(e.target.value)} className="w-full rounded-xl border border-slate-200 bg-white py-3 pl-10 pr-3 outline-none focus:ring-2 focus:ring-indigo-500" placeholder="you@rancholabs.com"/></div></label><label className="block text-sm font-medium">Password<div className="mt-2 relative"><LockKeyhole className="absolute left-3 top-3.5 h-4 w-4 text-slate-400"/><input required minLength={6} type={show?'text':'password'} value={password} onChange={e=>setPassword(e.target.value)} className="w-full rounded-xl border border-slate-200 bg-white py-3 pl-10 pr-11 outline-none focus:ring-2 focus:ring-indigo-500" placeholder="••••••••"/><button type="button" onClick={()=>setShow(!show)} className="absolute right-3 top-3.5 text-slate-400">{show?<EyeOff className="h-4 w-4"/>:<Eye className="h-4 w-4"/>}</button></div></label>{error&&<div className="rounded-xl bg-red-50 px-3 py-2 text-sm text-red-700">{error}</div>}<button disabled={busy} className="w-full rounded-xl bg-slate-950 py-3 text-sm font-semibold text-white hover:bg-slate-800 disabled:opacity-60">{busy?'Signing in…':'Sign in'}</button></form><button onClick={reset} className="mt-4 text-sm font-semibold text-indigo-600 hover:text-indigo-700">Forgot password?</button><div className="mt-6 flex items-center gap-2 text-xs text-slate-400"><ShieldCheck className="h-4 w-4"/>Protected with Supabase Auth and row-level security.</div></section></main>;
}
