import { CalendarDays, Camera, CheckCircle2, Clock3 } from 'lucide-react';
import Link from 'next/link';
import AppShell from '@/components/AppShell';
import { createServerSupabaseClient } from '@/lib/supabase/server';

export default async function DashboardPage(){
 const supabase=await createServerSupabaseClient(); const {data:{user}}=await supabase.auth.getUser();
 const {data:profile}=await supabase.from('profiles').select('*').eq('id',user?.id ?? '').single();
 const today=new Date().toISOString().slice(0,10);
 const {data:todayAttendance}=await supabase.from('attendance').select('*').eq('user_id',user?.id ?? '').eq('attendance_date',today).maybeSingle();
 const {count}=await supabase.from('attendance').select('*',{count:'exact',head:true}).eq('user_id',user?.id ?? '').gte('attendance_date',`${today.slice(0,7)}-01`);
 return <AppShell><div className="flex flex-col gap-8"><header><p className="text-sm font-semibold text-indigo-600">Instructor workspace</p><h1 className="mt-1 text-3xl font-bold tracking-tight">Good to see you, {profile?.full_name?.split(' ')[0] ?? 'Instructor'}.</h1><p className="mt-1 text-slate-500">Record your office attendance with a live camera check-in.</p></header><div className="grid gap-5 md:grid-cols-3"><div className="surface rounded-2xl p-5"><div className="flex items-center justify-between"><span className="text-sm text-slate-500">Today&apos;s status</span><CheckCircle2 className={`h-5 w-5 ${todayAttendance?'text-emerald-600':'text-slate-300'}`}/></div><div className="mt-4 text-2xl font-bold">{todayAttendance?'Checked In':'Not Checked In'}</div><div className="mt-1 text-sm text-slate-400">{todayAttendance?new Date(todayAttendance.check_in_at).toLocaleTimeString('en-IN',{hour:'2-digit',minute:'2-digit'}):'Complete your check-in before starting work.'}</div></div><div className="surface rounded-2xl p-5"><div className="flex items-center justify-between"><span className="text-sm text-slate-500">Current date</span><CalendarDays className="h-5 w-5 text-indigo-500"/></div><div className="mt-4 text-xl font-bold">{new Date().toLocaleDateString('en-IN',{day:'2-digit',month:'long',year:'numeric'})}</div><div className="mt-1 text-sm text-slate-400">India Standard Time</div></div><div className="surface rounded-2xl p-5"><div className="flex items-center justify-between"><span className="text-sm text-slate-500">This month</span><Clock3 className="h-5 w-5 text-cyan-500"/></div><div className="mt-4 text-2xl font-bold">{count ?? 0} <span className="text-base font-medium text-slate-400">check-ins</span></div><div className="mt-1 text-sm text-slate-400">Based on recorded attendance</div></div></div><div className="surface overflow-hidden rounded-3xl p-7"><div className="flex flex-col gap-5 md:flex-row md:items-center md:justify-between"><div><p className="text-sm font-semibold text-indigo-600">Live verification</p><h2 className="mt-1 text-2xl font-bold">Ready to check in?</h2><p className="mt-2 max-w-2xl text-sm leading-6 text-slate-500">Use the device camera to capture a fresh selfie. The official attendance time is created on the server, and your image is kept in private storage.</p></div><Link href={todayAttendance?'/history':'/check-in'} className="inline-flex items-center justify-center gap-2 rounded-xl bg-slate-950 px-5 py-3 text-sm font-semibold text-white hover:bg-slate-800">{todayAttendance?<CalendarDays className="h-4 w-4"/>:<Camera className="h-4 w-4"/>}{todayAttendance?'View history':'Start camera check-in'}</Link></div></div></div></AppShell>;
}
